# Generated by Django 5.0.2 on 2024-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
        migrations.AddField(
            model_name='users',
            name='yearofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
