# Generated by Django 5.0.2 on 2024-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_member_products_rename_yearofbirth_users_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=7)),
            ],
        ),
    ]
