# Generated by Django 5.0.2 on 2024-02-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='message',
            field=models.TextField(default='i have been on previous medicine'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=0.0004940711462450593),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(default='department 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='surgeon', max_length=70),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(default='precious', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=725371846, max_length=12),
        ),
    ]
